# Generated by Django 5.0.7 on 2024-07-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=50, unique=True)),
                ('work', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Cooperative',
            },
        ),
        migrations.CreateModel(
            name='CoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
                ('co_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_at_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'co_users',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=16, unique=True, verbose_name='National ID')),
                ('name', models.CharField(max_length=100, verbose_name='Farmer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('co_name', models.CharField(max_length=100, verbose_name='Co Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
            ],
            options={
                'db_table': 'Farmers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('co_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=50)),
                ('enddate', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Season',
            },
        ),
        migrations.CreateModel(
            name='Selle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_name', models.CharField(max_length=10)),
                ('customer_National_id', models.CharField(max_length=16)),
                ('Customer_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
                ('unit_price', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20)),
                ('create_date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Selles',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storekeeper_id', models.CharField(max_length=10)),
                ('co_name', models.CharField(max_length=10)),
                ('farmer_id', models.CharField(max_length=16)),
                ('farmer_name', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.season')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
    ]
